@echo off
setlocal enableextensions

REM
REM Generated by ${generator.signature} on ${generated.timestamp}
REM
REM For more details and options on Android emulator, check out
REM https://developer.android.com/studio/run/emulator-commandline
REM

set ANDROID_SDK_ROOT=%USERPROFILE%\.nexial\${sdk.rel.path}
cd %ANDROID_SDK_ROOT%\emulator
emulator -avd ${avd.id} -ranchu -phone-number 2136394251 -allow-host-audio

REM -skindir %ANDROID_SDK_ROOT%\skins -skin ${skin}
REM -memory 1536
REM -camera-back virtualscene -camera-front emulated
REM -netfast -netspeed full -netdelay none
REM -timezone America/Los_Angeles
REM -no-wwindow

:end
endlocal
