@echo off
setlocal enableextensions

REM -----------------------------------------------------------------------------------------------
REM Generated by ${generator.signature} on ${generated.timestamp}
REM
REM For more details and options on Android emulator, check out
REM     https://developer.android.com/studio/run/emulator-commandline
REM -----------------------------------------------------------------------------------------------

REM For more details on these environment variables, check out
REM     https://nexiality.github.io/documentation/commands/mobile/batch-files/run-android-emulator
:setup_env
REM set EMULATOR_TIMEZONE=
REM set EMULATOR_MEMORY=
REM set EMULATOR_HEADLESS=
REM set EMULATOR_FRONT_CAM=
REM set EMULATOR_BACK_CAM=
REM set EMULATOR_PHONE=

if "%NEXIAL_HOME%" == "" ( set NEXIAL_HOME=C:\projects\nexial-core )
%NEXIAL_HOME%\bin\mobile\run-android-emulator.cmd ${avd.id}

:end
endlocal
