#!/usr/bin/env bash

#
# Generated by ${generator.signature} on ${generated.timestamp}
#
# For more details and options on Android emulator, check out
# https://developer.android.com/studio/run/emulator-commandline
#

export ANDROID_SDK_ROOT=~/.nexial/${sdk.rel.path}
cd $ANDROID_SDK_ROOT/emulator

emulator -avd ${avd.id} -ranchu -phone-number 2136394251 -allow-host-audio

# -skindir $ANDROID_SDK_ROOT/skins -skin ${skin}
# -memory 1536
# -camera-back virtualscene -camera-front emulated
# -netfast -netspeed full -netdelay none
# -timezone America/Los_Angeles
# -no-wwindow

