#!/usr/bin/env bash

#
# Generated by ${generator.signature} on ${generated.timestamp}
#
# For more details and options on ADB, check out
# https://developer.android.com/studio/command-line/adb#devicestatus
#

export ANDROID_SDK_ROOT=~/.nexial/${sdk.rel.path}
cd $ANDROID_SDK_ROOT/platform-tools

adb devices -l
