@echo off
setlocal enableextensions

REM
REM Generated by ${generator.signature} on ${generated.timestamp}
REM
REM For more details and options on ADB, check out
REM https://developer.android.com/studio/command-line/adb#devicestatus
REM

set ANDROID_SDK_ROOT=%USERPROFILE%\.nexial\${sdk.rel.path}
cd %ANDROID_SDK_ROOT%\platform-tools

adb devices -l

:end
endlocal
pause
