echo "NEXIAL_OUTPUT         = ${NEXIAL_OUTPUT}"
export NEXIAL_OUTPUT=${NEXIAL_OUTPUT}

echo "NEXIAL_EXECUTION_HTML = ${NEXIAL_EXECUTION_HTML}"
export NEXIAL_EXECUTION_HTML=${NEXIAL_EXECUTION_HTML}

echo "NEXIAL_JUNIT_XML      = ${NEXIAL_JUNIT_XML}"
export NEXIAL_JUNIT_XML=${NEXIAL_JUNIT_XML}

echo "NEXIAL_SUCCESS_RATE   = ${NEXIAL_SUCCESS_RATE}"
export NEXIAL_SUCCESS_RATE=${NEXIAL_SUCCESS_RATE}

echo "NEXIAL_EXIT_STATUS    = ${NEXIAL_EXIT_STATUS}"
export NEXIAL_EXIT_STATUS=${NEXIAL_EXIT_STATUS}
