@echo off

echo NEXIAL_OUTPUT=${NEXIAL_OUTPUT}
set NEXIAL_OUTPUT=${NEXIAL_OUTPUT}

echo NEXIAL_EXECUTION_HTML=${NEXIAL_EXECUTION_HTML}
set NEXIAL_EXECUTION_HTML=${NEXIAL_EXECUTION_HTML}

echo NEXIAL_JUNIT_XML=${NEXIAL_JUNIT_XML}
set NEXIAL_JUNIT_XML=${NEXIAL_JUNIT_XML}

echo NEXIAL_SUCCESS_RATE=${NEXIAL_SUCCESS_RATE}
set NEXIAL_SUCCESS_RATE=${NEXIAL_SUCCESS_RATE}

echo NEXIAL_EXIT_STATUS=${NEXIAL_EXIT_STATUS}
set NEXIAL_EXIT_STATUS=${NEXIAL_EXIT_STATUS}
