# Description: Build and test nexial core
# Author: Sai Karthik <kskarthik@disroot.org>
# TODO: Investigate what causes build failure on windows
# TODO: Check why unit tests fail
name: Nexial Core CI

# run jobs on master branches & pull requests
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # build nexial-core
  build:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Run gradle build on linux & mac
      if: runner.os != 'Windows'
      run: cd support/ && bash build.sh

    #- name: Run gradle build on windows
    #  if: runner.os == 'Windows'
    #  run: cd support && .\build.cmd

  # run tests for nexial-core  
  test:
    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 19
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6
      
    - name: Run tests on linux & mac
      if: runner.os != 'Windows'
      run: cd support/ && bash build.sh -t
